version: "3.8"

services:
  backend:
    build:
      context: ./backend/backend
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    networks:
      - copilotdemo-network

  mobile:
    build:
      context: ./mobile
      dockerfile: Dockerfile
    ports:
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
    networks:
      - copilotdemo-network

networks:
  copilotdemo-network:
    driver: bridge
