version: "3.8"

services:
  backend:
    build:
      context: ./backend/backend
      dockerfile: Dockerfile
    ports:
      - "5001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  mobile:
    build:
      context: ./mobile
      dockerfile: Dockerfile
    ports:
      - "8081:8081" # Change this line
      - "19001:19001"
      - "19002:19002"
    environment:
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
